In [1]:
import pandas as pd
import numpy as np

In [9]:
df = pd.read_csv('https://raw.githubusercontent.com/DSFBL/1_python_public/main/lesson_10-11/titanic.csv')

In [10]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [11]:
df.groupby('Sex')['Pclass'].value_counts()

Sex     Pclass
female  3         144
        1          94
        2          76
male    3         347
        1         122
        2         108
Name: Pclass, dtype: int64

In [12]:
df['Survived'][df['Survived']==1].count()

342

In [13]:
df['SibSp'].mean()
round(0.5230078563411896, 2)

0.52

In [14]:
df['Fare'].quantile(0.75)

31.0

In [15]:
df['Age'].mean()
mean = 29.69911764705882
df[(df['Sex'] == 'female') & (df['Pclass'] == 3) & (df['Age'] > mean)].count()

PassengerId    26
Survived       26
Pclass         26
Name           26
Sex            26
Age            26
SibSp          26
Parch          26
Ticket         26
Fare           26
Cabin           0
Embarked       26
dtype: int64

In [16]:
df.groupby('Sex')['Fare'].mean()
m = 44.479818
f = 25.523893
print(m - f)
round(18.955925, 2)

18.955925


18.96

In [17]:
df['Family'] = df['SibSp'] + df['Parch']
df.sort_values(by='Family', ascending=False).head(7)

PassengerId  Survived  Pclass                               Name     Sex  \
180          181         0       3       Sage, Miss. Constance Gladys  female   
846          847         0       3           Sage, Mr. Douglas Bullen    male   
792          793         0       3            Sage, Miss. Stella Anna  female   
201          202         0       3                Sage, Mr. Frederick    male   
159          160         0       3         Sage, Master. Thomas Henry    male   
863          864         0       3  Sage, Miss. Dorothy Edith "Dolly"  female   
324          325         0       3           Sage, Mr. George John Jr    male   

     Age  SibSp  Parch    Ticket   Fare Cabin Embarked  Family  
180  NaN      8      2  CA. 2343  69.55   NaN        S      10  
846  NaN      8      2  CA. 2343  69.55   NaN        S      10  
792  NaN      8      2  CA. 2343  69.55   NaN        S      10  
201  NaN      8      2  CA. 2343  69.55   NaN        S      10  
159  NaN      8      2  CA. 2343  69.55   NaN        S      10  
863  NaN      8      2  CA. 2343  69.55   NaN        S      10  
324  NaN      8      2  CA. 2343  69.55   NaN        S      10

In [43]:
def get_first_name(string):
    return string.split('. ')[1].split(' ')[0]
df['FirstName'] = df['Name'].apply(get_first_name)
df['FirstName'].value_counts()

William    48
John       31
Thomas     19
Charles    16
George     16
           ..
Roberta     1
Nikola      1
Achille     1
Theodor     1
Oskar       1
Name: FirstName, Length: 441, dtype: int64

In [ ]:
def get_first_name_upd(string):
    return string.split('(')[0].split(')')[1]
df['FirstNameUpd'] = df['Name'].apply(get_first_name_upd)
df['FirstNameUpd'].value_counts()

In [60]:
df['Name'].loc[0].split('(').split(')')[0]

AttributeError: 'list' object has no attribute 'split'

In [35]:
a = np.array([[123, 14, -18], [1245, 0, 53]])
b = np.array([[-56, 78], [45, 983], [-12, 15]])
c = a @ b
print(c)

[[ -6042  23086]
 [-70356  97905]]


[[ -6042  23086]
 [-70356  97905]]


In [68]:
x = [2, 2, 2, 3, 3, 3, 5]
unique = []
repeat = []
count = 0
for i in range(7):
    count += 1
    if i != (len(x)-1):
        if x[i] != x[i + 1]:
            repeat.append(count)
            unique.append(x[i])
            count = 0
    else:
        unique.append(x[i])
        repeat.append(count)
import numpy as np
repeat = np.array(repeat)
unique = np.array(unique)
print(unique)
print(repeat)

[2 3 5]
[3 3 1]
